### ISSUE TITLE
Connecting to device using example code hangs on DeviceScreen

### ISSUE THREAD

**Issue by BikeBr0** [jkdhn/mcumgr-dart#2]
Trying to use your example code to connect to a Bluetooth Device and the App hangs on the DeviceScreen. handleConnectionState is only called once (event.connectionState is "connecting"). Does this example work?

**Comment by jkdhn** [comment]
The example isn't done, but I can successfully connect to a device and upload firmware.

I've only tested it on Android 12, I don't have an iOS phone to test it with.

**Comment by BikeBr0** [comment]
I am testing in Android 12 as well (Pixel 6). When I place a breakpoint on handleConnectionState in device.dart, I can see it is only ever called once. I'll more diligently clone your repo and try again.

**Comment by BikeBr0** [comment]
I see, it does indeed work on Android 12. My peripheral does not support autoconnect, which is the default behaviour of [flutter_reactive_ble](https://github.com/PhilipsHue/flutter_reactive_ble) when a connectionTimeout is not provided (and is null in the example code).
