### ISSUE TITLE
How long lived should a Client be?

### ISSUE THREAD

**Issue by BikeBr0** [jkdhn/mcumgr-dart#3]
I'm not sure the best way to ask you a general question, so I'll pose it as an "issue"...

How long lived should a Client object be? Make one command and dispose of it? Or should it be possible to use one Client for an entire Bluetooth connection?

**Comment by jkdhn** [comment]
I'd recommend using one client for the whole connection.

Using multiple clients at the same time is dangerous (the message sequence number could collide) and making clients long-lived is the safest way to avoid that. There will also be problems if you create a client while a fragmented response is being received (it will start parsing the response stream in the middle of a response).

**Comment by BikeBr0** [comment]
Thank you @jkdhn! That helps me to know I was on the right track. I ask because I am running into a problem with my own code when re-using the Client for multiple echo commands (implementing multiple echo commands within your example app works fine).

Basically, I added an "Echo" button to your device screen that opens the following StatefulWidget in a bottom sheet:

```
import 'package:flutter/material.dart';
import 'package:mcumgr/mcumgr.dart';
import 'package:titan_app/bluetooth/titan_device.dart';

class EchoCommand extends StatefulWidget {
  final TextEditingController txtController = TextEditingController();
  final TitanDevice device;

  EchoCommand(this.device, {Key? key, String? text}) : super(key: key) {
    txtController.text = text ?? '';
  }

  @override
  State<StatefulWidget> createState() => _EchoCommandState();
}

class _EchoCommandState extends State<EchoCommand> {

  String _response = '';

  _echo(String msg) async {
    Client client = widget.device.client!;
    String response = await client.echo(msg, const Duration(seconds: 5));
    setState(() {
      _response = response;
    });
  }
  
  @override
  Widget build(BuildContext context) {
    final widgets = <Widget>[
      Card(
        child: ListTile(
          leading: const Icon(Icons.abc),
          title: TextField(
            controller: widget.txtController,
            onSubmitted: (text) async {
              _echo(text);
            },
          )
        ),
      ),
      Card(
        child: ListTile(
          leading: const Icon(Icons.comment),
          title: Text(_response)
        ),
      )
    ];
    return SingleChildScrollView(
      child: Column(
        children: widgets,
      ),
    );
  }
}
```
This creates a UI to enter text and display the echoed response.

The first time it is ran, the echo command works as expected and the correct text is displayed. Subsequent attempts, however, throw an exception:

```
E/flutter ( 9600): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Stream has already been listened to.
E/flutter ( 9600): #0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
E/flutter ( 9600): #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
E/flutter ( 9600): #2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
E/flutter ( 9600): #3      Smp.decode.<anonymous closure>                                                 package:mcumgr/…/smp/smp.dart:23
E/flutter ( 9600): #4      _runGuarded (dart:async/stream_controller.dart:814:24)
E/flutter ( 9600): #5      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
E/flutter ( 9600): #6      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
E/flutter ( 9600): #7      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
E/flutter ( 9600): #8      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
E/flutter ( 9600): #9      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
E/flutter ( 9600): #10     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
E/flutter ( 9600): #11     Stream.timeout.<anonymous closure> (dart:async/stream.dart:1598:31)
E/flutter ( 9600): #12     _runGuarded (dart:async/stream_controller.dart:814:24)
E/flutter ( 9600): #13     _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
E/flutter ( 9600): #14     _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
E/flutter ( 9600): #15     _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
E/flutter ( 9600): #16     Stream.first (dart:async/stream.dart:1280:14)
E/flutter ( 9600): #17     Client._execute                                                                                  package:mcumgr/client.dart:41
E/flutter ( 9600): #18     Client.execute                                                                                   package:mcumgr/client.dart:105
E/flutter ( 9600): #19     ClientOsExtension.echo                                                                    package:mcumgr/os.dart:15
E/flutter ( 9600): #20     _EchoCommandState._echo
```

Do you have any idea why the client is only able to execute one command in this example?

**Comment by jkdhn** [comment]
That's because the client creates a new subscription to the input stream every time you run a command, which flutter_reactive_ble doesn't allow. I changed that in 37bb5bde0c78942664dd61124e5c930967f34b80, but didn't release a new version yet because there are still some problems with error handling.

For now, you could just pass `.asBroadcastStream()` to the client.

**Comment by BikeBr0** [comment]
That worked! Now my Client instantiation looks like:

```
final client = Client(
  input: _ble.subscribeToCharacteristic(characteristic).asBroadcastStream(),
  output: (msg) => _ble.writeCharacteristicWithoutResponse(characteristic, value: msg),
);
```

I did notice that my App crashes when I disconnect from the peripheral. Is this the error you are referring to?

```
W/System.err(26516): io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: [https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling]() | com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 0 (GATT_SUCCESS)
```

**Comment by BikeBr0** [comment]
I was able to prevent the disconnect error by changing the Client instantiation as follows:

```
_client = Client(
  input: _ble.subscribeToCharacteristic(characteristic).asBroadcastStream(onListen: (subscription) {
    _subscription = subscription;
  }),
  output: (msg) => _ble.writeCharacteristicWithoutResponse(characteristic, value: msg),
);
```

And then calling 

```
_subscription?.cancel();
_connection?.cancel();
```

When disconnecting from the peripheral.

**Comment by jkdhn** [comment]
The [the flutter_reactive_ble FAQ](https://github.com/PhilipsHue/flutter_reactive_ble#how-to-handle-the-ble-undeliverable-exception) contains a workaround for that exception.

I don't think canceling the subscription is enough, I still got that exception rarely (until I added that workaround in 0fe4cdcb029a8a47e1dc323e2711986002ca681a).

I also added some code to the example to completely ignore errors in the subscription stream because I occasionally got stale "disconnected" errors in the new connection after reconnecting to the device. Disconnecting causes the subscription stream to end anyways, so I'm not sure why that error even exists.

**Comment by BikeBr0** [comment]
Okay, I used your linked workaround and that seems to work. I'll update to 0.0.3 once it is available.
