### ISSUE TITLE
How to send .zip file to device

### ISSUE THREAD

**Issue by b2infosoft-manoj** [jkdhn/mcumgr-dart#9]
I can send .bin file successfully but now I want to send zip file to device, please guide how can I do this.

**Comment by BikeBr0** [comment]
I had to do this too and implemented my own uploadFile file method as an extension on Client (mcumgr/client.dart). The peripheral should have built in support for this through MCUMGR. Here is a snippet of code to help:

```
  /// A method to upload a file chunk
  Future<FileUploadProgress> _uploadFileChunk(Uint8List chunk, int offset, int length, String name, {Duration timeout = const Duration(seconds: 10)}) async {

    var map = CborMap({
      CborValue('off'): CborInt(BigInt.from(offset)),
      CborValue('data'): CborBytes(chunk.toList()),
      CborValue('name'): CborString('/lfs/$name'),
    });

    if (offset == 0) {
      map[CborValue('len')] = CborInt(BigInt.from(length));
    }

    return execute(
      Message(
        op: Operation.write,
        group: _fsGroup,
        id: _fileDownloadUpload,
        flags: 0,
        data: map,
      ),
      timeout,
    ).unwrap().then((value) {
      final rc = (value.data[CborString('rc')] as CborSmallInt).toInt();
      final returnedOffset = (value.data[CborString('off')] as CborSmallInt).toInt();
      return FileUploadProgress(returnedOffset, rc);
    });
  }
```

**Comment by b2infosoft-manoj** [comment]
could you please advise how to use this method to upload .zip file? my zip file have 2 .bin file and one .json file

**Comment by jkdhn** [comment]
Seems like you're talking about uploading firmware to a multi-image device such as nRF5340?
You will have to upload both .bin files using `uploadImage`.
`manifest.json` contains a property called `image_index`, pass that as the `image` parameter when calling `uploadImage` to tell the device whether the image should be written to the application core or network core.
Unfortunately I currently can't test this myself because I only have nRF52840 boards.

**Comment by BikeBr0** [comment]
Hi @keyss-manoj, yes I can but if @jkdhn's assessment is correct, I suggest you follow his advice. Please advise.

**Comment by b2infosoft-manoj** [comment]
Hi @BikeBr0 , @jkdhn suggestion worked fine, thanks for great support.
